### PR TITLE
Resolve exceptions

### PR DESCRIPTION
**Pull request by iicey**
Resolve exceptions: "wasm function signature contains illegal type"

### CODE REVIEW

**Comment by donmccurdy** [comment]
Thanks @iicey! Could you help me understand what is being changed to fix this issue? Are you recompiling the WASM from some particular version of the zstd decoder, and if so which version?  Do any of the compile steps differ from what's documented in https://github.com/donmccurdy/zstddec#building-from-source? 

I do notice that the bundle size increases from 43kb to 69kb, even after removing the comment — which could be a result of differences in the source version or compile steps perhaps.

**Comment by wiedehopf** [comment]
The increased size is probably due to -O3 instead of -Os. (very roughly 25 % improvement in decompression speed on an 11th gen intel laptop)

@iicey PRs don't suit themselves to binary blobs, i'm sure you meant well but really if you have some standards and publish on github you need to compile binary distributibles yourself :)

**Comment by iicey** [comment]
I don't know how it compiled successfully. Wasm was stolen from the JS file linked below
https://globe.adsbexchange.com/libs_cd451740ed627c644137b1dfe3a415a1.js

**Comment by wiedehopf** [comment]
https://github.com/wiedehopf/zstddec-tar1090#compiling-the-wasm-from-source

@iicey the above link describes everything you need to compile the wasm from official sources.

It uses zstd 1.5.0 and makes the findDecompressedSize interface return a 32bit value which is what fixes the described exceptions:
https://github.com/wiedehopf/zstddec-tar1090/blob/master/changes.diff

**Pull request closed without merging**
